In [1]:
import pandas as pd
import numpy as np

In [4]:
data = np.random.rand(2,4,3)
data

array([[[ 0.21239813,  0.12363062,  0.84559852],
        [ 0.71292152,  0.58041479,  0.53164612],
        [ 0.42433546,  0.01345998,  0.0747192 ],
        [ 0.49293736,  0.33662643,  0.6440573 ]],

       [[ 0.14330514,  0.10200316,  0.34649389],
        [ 0.53063132,  0.8197673 ,  0.73708549],
        [ 0.39873256,  0.09463729,  0.79307407],
        [ 0.88132084,  0.61828463,  0.23540874]]])

In [9]:
p = pd.Panel(data)
p

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 4 (major_axis) x 3 (minor_axis)
Items axis: 0 to 1
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 2

In [10]:
p.values

array([[[ 0.21239813,  0.12363062,  0.84559852],
        [ 0.71292152,  0.58041479,  0.53164612],
        [ 0.42433546,  0.01345998,  0.0747192 ],
        [ 0.49293736,  0.33662643,  0.6440573 ]],

       [[ 0.14330514,  0.10200316,  0.34649389],
        [ 0.53063132,  0.8197673 ,  0.73708549],
        [ 0.39873256,  0.09463729,  0.79307407],
        [ 0.88132084,  0.61828463,  0.23540874]]])

In [21]:
p.transpose(0,1,2).values

array([[[ 0.21239813,  0.12363062,  0.84559852],
        [ 0.71292152,  0.58041479,  0.53164612],
        [ 0.42433546,  0.01345998,  0.0747192 ],
        [ 0.49293736,  0.33662643,  0.6440573 ]],

       [[ 0.14330514,  0.10200316,  0.34649389],
        [ 0.53063132,  0.8197673 ,  0.73708549],
        [ 0.39873256,  0.09463729,  0.79307407],
        [ 0.88132084,  0.61828463,  0.23540874]]])

In [23]:
df = p.to_frame()
df

                    0         1
major minor
0     0      0.212398  0.143305
      1      0.123631  0.102003
      2      0.845599  0.346494
1     0      0.712922  0.530631
      1      0.580415  0.819767
      2      0.531646  0.737085
2     0      0.424335  0.398733
      1      0.013460  0.094637
      2      0.074719  0.793074
3     0      0.492937  0.881321
      1      0.336626  0.618285
      2      0.644057  0.235409

In [24]:
df.values

array([[ 0.21239813,  0.14330514],
       [ 0.12363062,  0.10200316],
       [ 0.84559852,  0.34649389],
       [ 0.71292152,  0.53063132],
       [ 0.58041479,  0.8197673 ],
       [ 0.53164612,  0.73708549],
       [ 0.42433546,  0.39873256],
       [ 0.01345998,  0.09463729],
       [ 0.0747192 ,  0.79307407],
       [ 0.49293736,  0.88132084],
       [ 0.33662643,  0.61828463],
       [ 0.6440573 ,  0.23540874]])

In [32]:
rng = pd.date_range('1/1/2017', periods = 72, freq = 'H')
rng

DatetimeIndex(['2017-01-01 00:00:00', '2017-01-01 01:00:00',
               '2017-01-01 02:00:00', '2017-01-01 03:00:00',
               '2017-01-01 04:00:00', '2017-01-01 05:00:00',
               '2017-01-01 06:00:00', '2017-01-01 07:00:00',
               '2017-01-01 08:00:00', '2017-01-01 09:00:00',
               '2017-01-01 10:00:00', '2017-01-01 11:00:00',
               '2017-01-01 12:00:00', '2017-01-01 13:00:00',
               '2017-01-01 14:00:00', '2017-01-01 15:00:00',
               '2017-01-01 16:00:00', '2017-01-01 17:00:00',
               '2017-01-01 18:00:00', '2017-01-01 19:00:00',
               '2017-01-01 20:00:00', '2017-01-01 21:00:00',
               '2017-01-01 22:00:00', '2017-01-01 23:00:00',
               '2017-01-02 00:00:00', '2017-01-02 01:00:00',
               '2017-01-02 02:00:00', '2017-01-02 03:00:00',
               '2017-01-02 04:00:00', '2017-01-02 05:00:00',
               '2017-01-02 06:00:00', '2017-01-02 07:00:00',
               '2017-01-02 08:00:00', '2017-01-02 09:00:00',
               '2017-01-02 10:00:00', '2017-01-02 11:00:00',
               '2017-01-02 12:00:00', '2017-01-02 13:00:00',
               '2017-01-02 14:00:00', '2017-01-02 15:00:00',
               '2017-01-02 16:00:00', '2017-01-02 17:00:00',
               '2017-01-02 18:00:00', '2017-01-02 19:00:00',
               '2017-01-02 20:00:00', '2017-01-02 21:00:00',
               '2017-01-02 22:00:00', '2017-01-02 23:00:00',
               '2017-01-03 00:00:00', '2017-01-03 01:00:00',
               '2017-01-03 02:00:00', '2017-01-03 03:00:00',
               '2017-01-03 04:00:00', '2017-01-03 05:00:00',
               '2017-01-03 06:00:00', '2017-01-03 07:00:00',
               '2017-01-03 08:00:00', '2017-01-03 09:00:00',
               '2017-01-03 10:00:00', '2017-01-03 11:00:00',
               '2017-01-03 12:00:00', '2017-01-03 13:00:00',
               '2017-01-03 14:00:00', '2017-01-03 15:00:00',
               '2017-01-03 16:00:00', '2017-01-03 17:00:00',
               '2017-01-03 18:00:00', '2017-01-03 19:00:00',
               '2017-01-03 20:00:00', '2017-01-03 21:00:00',
               '2017-01-03 22:00:00', '2017-01-03 23:00:00'],
              dtype='datetime64[ns]', freq='H')